import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ArrowRight, BriefcaseBusiness, Compass, Menu, MessageCircle, Moon, Search, ShieldCheck, Sun, UserRound, X } from "lucide-react";
import { useState } from "react";
import { Link, Route, Switch, useLocation } from "wouter";
import ErrorBoundary from "./components/ErrorBoundary";
import { ThemeProvider, useTheme } from "./contexts/ThemeContext";
import AuthPage from "./pages/AuthPage";
import Home from "./pages/Home";
import NotFound from "./pages/NotFound";
import { BecomeDeveloperPage, ClientDashboardPage, DeveloperDashboardPage, DeveloperProfilePage, ExploreProjectsPage, FindDeveloperPage, HelpSecurityPage, ProjectDetailPage } from "./pages/MarketplacePages";

const navItems = [{ label: "Développeurs", href: "/explorer" }, { label: "Projets", href: "/projets" }, { label: "Comment ça marche", href: "/#fonctionnement" }];
function BrandMark({ inverse = false }: { inverse?: boolean }) { return <Link href="/" className="group flex items-center gap-2.5" aria-label="DevConnect, accueil"><span className={`grid h-9 w-9 place-items-center rounded-xl text-lg font-black shadow-sm transition-transform duration-200 group-hover:-rotate-6 ${inverse ? "bg-white text-[#1557f5]" : "bg-[#1557f5] text-white"}`}>D</span><span className={`font-display text-[1.3rem] font-bold tracking-[-.04em] ${inverse ? "text-white" : "text-ink"}`}>Dev<span className={inverse ? "text-[#f4a35d]" : "text-[#e4793f]"}>Connect</span></span></Link>; }
function AppHeader() { const [open, setOpen] = useState(false); const [location] = useLocation(); const { resolvedTheme, toggleTheme } = useTheme(); return <header className="sticky top-0 z-50 border-b border-black/[.06] bg-[#fbfaf7]/90 backdrop-blur-xl"><div className="container flex h-[72px] items-center justify-between gap-5"><BrandMark /><nav className="hidden items-center gap-7 text-sm font-semibold text-ink/60 lg:flex" aria-label="Navigation principale">{navItems.map((item) => <Link key={item.href} href={item.href} className={`transition-colors hover:text-ink ${location === item.href ? "text-ink" : ""}`}>{item.label}</Link>)}</nav><div className="hidden items-center gap-2 sm:flex"><button onClick={toggleTheme} className="grid h-10 w-10 place-items-center rounded-full border border-ink/10 text-ink/60 transition hover:bg-ink/[.04] hover:text-ink" aria-label="Changer de thème">{resolvedTheme === "dark" ? <Sun size={17} /> : <Moon size={17} />}</button><Link href="/connexion" className="rounded-full px-4 py-2.5 text-sm font-semibold text-ink/70 transition-colors hover:bg-ink/[.04] hover:text-ink">Se connecter</Link><Link href="/publier" className="inline-flex items-center gap-2 rounded-full bg-ink px-4 py-2.5 text-sm font-semibold text-white shadow-[0_6px_20px_rgba(19,28,35,.12)]">Publier un projet <ArrowRight size={15} /></Link></div><div className="flex items-center gap-2 sm:hidden"><button onClick={toggleTheme} className="grid h-10 w-10 place-items-center rounded-full border border-ink/10 text-ink/60" aria-label="Changer de thème">{resolvedTheme === "dark" ? <Sun size={17} /> : <Moon size={17} />}</button><button className="grid h-10 w-10 place-items-center rounded-full border border-ink/10 text-ink" onClick={() => setOpen(!open)} aria-label="Ouvrir le menu">{open ? <X size={19} /> : <Menu size={19} />}</button></div></div>{open && <div className="border-t border-black/[.06] bg-[#fbfaf7] px-5 py-4 sm:hidden"><nav className="container flex flex-col gap-1 text-sm font-semibold text-ink/70">{navItems.map((item) => <Link onClick={() => setOpen(false)} key={item.href} href={item.href} className="rounded-xl px-3 py-3 hover:bg-black/[.04]">{item.label}</Link>)}<div className="mt-2 grid grid-cols-2 gap-2 border-t border-black/[.06] pt-3"><Link onClick={() => setOpen(false)} href="/connexion" className="rounded-xl border border-ink/10 px-3 py-3 text-center">Se connecter</Link><Link onClick={() => setOpen(false)} href="/publier" className="rounded-xl bg-ink px-3 py-3 text-center text-white">Publier</Link></div></nav></div>}</header>; }
function MobileBar() { const [location] = useLocation(); const items = [{ href: "/", icon: Compass, label: "Accueil" }, { href: "/explorer", icon: Search, label: "Explorer" }, { href: "/publier", icon: BriefcaseBusiness, label: "Publier" }, { href: "/dashboard", icon: UserRound, label: "Espace" }]; return <nav className="fixed inset-x-3 bottom-3 z-50 grid grid-cols-4 rounded-2xl border border-black/10 bg-white/95 p-1.5 shadow-[0_12px_40px_rgba(19,28,35,.16)] backdrop-blur-xl sm:hidden" aria-label="Navigation mobile">{items.map(({ href, icon: Icon, label }) => <Link key={href} href={href} className={`flex flex-col items-center gap-1 rounded-xl px-2 py-2 text-[10px] font-semibold transition ${location === href ? "bg-ink text-white" : "text-ink/45"}`}><Icon size={17} /><span>{label}</span></Link>)}</nav>; }
function AppLayout({ children }: { children: React.ReactNode }) { return <div className="min-h-screen bg-[#fbfaf7] text-ink"><AppHeader />{children}<MobileBar /></div>; }
function PublishPage() { return <AppLayout><main className="container max-w-5xl py-10 sm:py-16"><div className="grid gap-10 lg:grid-cols-[1fr_320px]"><div><p className="eyebrow">Lancer un projet</p><h1 className="mt-3 font-display text-4xl font-bold tracking-[-.055em] sm:text-6xl">Décrivez ce que vous voulez <span className="text-coral">construire.</span></h1><p className="mt-4 max-w-xl text-base leading-7 text-ink/55">Présentez votre besoin pour recevoir des réponses de développeurs inscrits sur DevConnect.</p><div className="mt-10 space-y-5 rounded-[28px] border border-ink/10 bg-white p-5 shadow-[0_12px_40px_rgba(19,28,35,.06)] sm:p-8"><label className="block"><span className="label">Titre du projet</span><input className="field" placeholder="Ex. Créer une application mobile" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block"><span className="label">Catégorie</span><select className="field"><option>Choisir une catégorie</option><option>Développement web</option><option>Application mobile</option><option>IA & automatisation</option><option>Maintenance</option></select></label><label className="block"><span className="label">Budget estimé</span><input className="field" placeholder="Ex. 1 500 €" /></label></div><label className="block"><span className="label">Décrivez votre besoin</span><textarea className="field min-h-[140px] resize-y" placeholder="Objectifs, livrables, contexte et délai souhaité..." /></label><button className="inline-flex w-full items-center justify-center gap-2 rounded-full bg-ink px-5 py-3.5 text-sm font-bold text-white">Publier après connexion <ArrowRight size={16} /></button></div></div><aside className="hidden lg:block"><div className="sticky top-28 rounded-[28px] bg-[#eef2ff] p-6"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#1557f5] text-white"><ShieldCheck size={20} /></span><h2 className="mt-5 font-display text-xl font-bold">Un brief précis attire les bons profils.</h2><p className="mt-3 text-sm leading-6 text-ink/60">Votre publication sera associée à votre compte client et visible uniquement selon les règles de la marketplace.</p></div></aside></div></main></AppLayout>; }
function SimplePage({ title, description, icon: Icon = UserRound }: { title: string; description: string; icon?: typeof UserRound }) { return <AppLayout><main className="container flex min-h-[70vh] items-center justify-center py-16"><div className="max-w-lg text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#eaf0ff] text-[#1557f5]"><Icon size={24} /></span><h1 className="mt-6 font-display text-4xl font-bold tracking-[-.05em]">{title}</h1><p className="mt-4 leading-7 text-ink/55">{description}</p><Link href="/" className="mt-7 inline-flex items-center gap-2 rounded-full bg-ink px-5 py-3.5 text-sm font-bold text-white">Retour à l'accueil <ArrowRight size={16} /></Link></div></main></AppLayout>; }
function Router() { return <Switch><Route path="/" component={() => <AppLayout><Home /></AppLayout>} /><Route path="/explorer" component={() => <AppLayout><FindDeveloperPage /></AppLayout>} /><Route path="/trouver-un-developpeur" component={() => <AppLayout><FindDeveloperPage /></AppLayout>} /><Route path="/projets" component={() => <AppLayout><ExploreProjectsPage /></AppLayout>} /><Route path="/publier" component={PublishPage} /><Route path="/projet/:slug" component={() => <AppLayout><ProjectDetailPage /></AppLayout>} /><Route path="/profil/:slug" component={() => <AppLayout><DeveloperProfilePage /></AppLayout>} /><Route path="/devenir-developpeur" component={() => <AppLayout><BecomeDeveloperPage /></AppLayout>} /><Route path="/dashboard-client" component={() => <AppLayout><ClientDashboardPage /></AppLayout>} /><Route path="/dashboard-developpeur" component={() => <AppLayout><DeveloperDashboardPage /></AppLayout>} /><Route path="/dashboard" component={() => <AppLayout><ClientDashboardPage /></AppLayout>} /><Route path="/aide" component={() => <AppLayout><HelpSecurityPage /></AppLayout>} /><Route path="/connexion" component={() => <AppLayout><AuthPage /></AppLayout>} /><Route path="/admin" component={() => <SimplePage title="Espace administration" description="Cette zone est réservée aux comptes administrateurs vérifiés. L'accès est contrôlé par Supabase." icon={ShieldCheck} />} /><Route path="/messages" component={() => <SimplePage title="Messagerie" description="Vos échanges apparaîtront ici après votre inscription et vos premières missions." icon={MessageCircle} />} /><Route path="/404" component={NotFound} /><Route component={NotFound} /></Switch>; }
function App() { return <ErrorBoundary><ThemeProvider defaultTheme="system" switchable><TooltipProvider><Toaster /><Router /></TooltipProvider></ThemeProvider></ErrorBoundary>; }
export default App;
