import { ArrowRight, BadgeCheck, Check, ChevronRight, CircleDollarSign, Clock3, Code2, Layers3, LockKeyhole, Megaphone, Palette, Play, Quote, Sparkles, Star, UsersRound } from "lucide-react";
import { Link } from "wouter";

const HERO_IMAGE = "/devconnect-hero.jpg";

const categories = [
  { name: "Développement web", icon: Code2, count: "324 talents", tint: "bg-[#eaf0ff] text-[#1557f5]" },
  { name: "Design & UI/UX", icon: Palette, count: "182 talents", tint: "bg-[#fff1ed] text-[#e4793f]" },
  { name: "IA & automatisation", icon: Sparkles, count: "96 talents", tint: "bg-[#f4edff] text-[#8a58d6]" },
  { name: "Marketing digital", icon: Megaphone, count: "217 talents", tint: "bg-[#edf8f0] text-[#318653]" },
];

const projects = [
  { title: "Refonte e-commerce pour une marque de cosmétiques", category: "Développement web", budget: "1 500 – 2 500 €", proposals: 8, initials: "KM", tint: "bg-[#b7cee0]" },
  { title: "Identité visuelle pour une startup climate-tech", category: "Design graphique", budget: "800 – 1 200 €", proposals: 14, initials: "AD", tint: "bg-[#eec6a8]" },
  { title: "Assistant WhatsApp pour service client", category: "IA & automatisation", budget: "2 000 – 4 000 €", proposals: 6, initials: "NO", tint: "bg-[#cfc3e4]" },
];

const freelancers = [
  { name: "Awa Diop", role: "Product designer", city: "Dakar, Sénégal", rating: "4.9", initials: "AD", tint: "bg-[#eec6a8]" },
  { name: "Koffi Mensah", role: "Full-stack developer", city: "Abidjan, Côte d’Ivoire", rating: "5.0", initials: "KM", tint: "bg-[#b7cee0]" },
  { name: "Nia Okafor", role: "Brand strategist", city: "Lagos, Nigeria", rating: "4.8", initials: "NO", tint: "bg-[#cfc3e4]" },
];

function SectionHeading({ eyebrow, title, link }: { eyebrow: string; title: React.ReactNode; link?: string }) {
  return <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">{eyebrow}</p><h2 className="mt-3 max-w-2xl font-display text-3xl font-bold leading-[1.05] tracking-[-0.055em] text-ink sm:text-5xl">{title}</h2></div>{link && <Link href={link} className="inline-flex w-fit items-center gap-2 text-sm font-bold text-[#1557f5] transition hover:gap-3">Tout explorer <ArrowRight size={16} /></Link>}</div>;
}

export default function Home() {
  return <>
    <main>
      <section className="relative overflow-hidden bg-ink text-white">
        <div className="absolute inset-0 opacity-90" style={{ backgroundImage: `url(${HERO_IMAGE})`, backgroundPosition: "center right", backgroundSize: "cover" }} />
        <div className="absolute inset-0 bg-gradient-to-r from-ink via-ink/95 to-ink/20" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(21,87,245,.18),transparent_35%)]" />
        <div className="container relative flex min-h-[630px] items-center pb-16 pt-20 sm:min-h-[690px] sm:pb-24 sm:pt-24">
          <div className="max-w-3xl">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-2 text-xs font-semibold text-white/75 backdrop-blur"><span className="h-2 w-2 rounded-full bg-[#f4a35d]" /> La marketplace qui fait grandir l'Afrique numérique</div>
            <h1 className="max-w-2xl font-display text-5xl font-bold leading-[.98] tracking-[-0.07em] sm:text-7xl lg:text-[88px]">Les idées locales méritent des <span className="text-[#f4a35d]">talents extraordinaires.</span></h1>
            <p className="mt-7 max-w-xl text-base leading-7 text-white/65 sm:text-lg">DevConnect met en relation les entreprises ambitieuses avec les freelances qui comprennent leur réalité, leur marché et leur prochain chapitre.</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/publier" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#f4a35d] px-5 py-3.5 text-sm font-bold text-ink transition hover:-translate-y-0.5 hover:bg-[#ffc285]">Publier un projet <ArrowRight size={17} /></Link><Link href="/explorer" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/20 bg-white/10 px-5 py-3.5 text-sm font-bold text-white backdrop-blur transition hover:bg-white/15">Je suis freelance <ChevronRight size={17} /></Link></div>
            <div className="mt-12 flex flex-wrap items-center gap-x-8 gap-y-4 text-xs font-semibold text-white/45"><span className="flex items-center gap-2"><BadgeCheck size={16} className="text-[#f4a35d]" /> Profils vérifiés</span><span className="flex items-center gap-2"><LockKeyhole size={16} className="text-[#f4a35d]" /> Paiement à connecter</span><span className="flex items-center gap-2"><UsersRound size={16} className="text-[#f4a35d]" /> 12 pays représentés</span></div>
          </div>
        </div>
        <div className="container relative -mb-1"><div className="grid gap-3 border-t border-white/10 py-5 text-xs text-white/45 sm:grid-cols-3"><span><strong className="mr-1 font-display text-lg text-white">1 240+</strong> talents disponibles</span><span><strong className="mr-1 font-display text-lg text-white">380+</strong> projets lancés</span><span><strong className="mr-1 font-display text-lg text-white">4.9/5</strong> de satisfaction</span></div></div>
      </section>

      <section className="container py-20 sm:py-28"><SectionHeading eyebrow="Les expertises qui comptent" title={<>Tout ce qu'il faut pour passer de l'idée au <span className="text-coral">résultat.</span></>} link="/explorer" /><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{categories.map(({ name, icon: Icon, count, tint }) => <Link href="/explorer" key={name} className="group rounded-[22px] border border-ink/[0.08] bg-white p-5 shadow-[0_6px_24px_rgba(19,28,35,.04)] transition hover:-translate-y-1 hover:border-[#1557f5]/20 hover:shadow-[0_15px_30px_rgba(19,28,35,.08)]"><span className={`grid h-11 w-11 place-items-center rounded-2xl ${tint}`}><Icon size={20} /></span><h3 className="mt-8 font-display text-lg font-bold">{name}</h3><div className="mt-2 flex items-center justify-between text-xs font-semibold text-ink/40"><span>{count}</span><ArrowRight size={15} className="transition group-hover:translate-x-1 group-hover:text-[#1557f5]" /></div></Link>)}</div></section>

      <section className="bg-[#f1f3f1] py-20 sm:py-28"><div className="container"><SectionHeading eyebrow="Des projets qui avancent" title={<>Chaque mission est une <span className="text-coral">rencontre.</span></>} link="/projets" /><div className="mt-10 grid gap-4 lg:grid-cols-3">{projects.map((project) => <article key={project.title} className="group rounded-[24px] border border-ink/[0.08] bg-white p-5 shadow-[0_6px_24px_rgba(19,28,35,.04)] transition hover:-translate-y-1 hover:shadow-[0_15px_30px_rgba(19,28,35,.08)] sm:p-6"><div className="flex items-center justify-between"><span className="rounded-full bg-[#f2f0eb] px-3 py-1 text-[10px] font-bold uppercase tracking-[0.12em] text-ink/45">{project.category}</span><button aria-label="Ajouter le projet aux favoris" className="text-ink/25 transition hover:text-coral">☆</button></div><h3 className="mt-8 min-h-[76px] font-display text-xl font-bold leading-tight tracking-[-0.03em]">{project.title}</h3><div className="mt-6 flex items-center gap-3 border-t border-ink/[0.08] pt-4"><span className={`grid h-9 w-9 place-items-center rounded-xl ${project.tint} text-xs font-bold`}>{project.initials}</span><div className="min-w-0"><p className="text-xs font-semibold text-ink/45">Budget indicatif</p><p className="text-sm font-bold">{project.budget}</p></div><span className="ml-auto self-end text-xs text-ink/40">{project.proposals} prop.</span></div></article>)}</div></div></section>

      <section className="container py-20 sm:py-28"><div className="grid items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Simple par design</p><h2 className="mt-3 max-w-lg font-display text-4xl font-bold leading-[1.02] tracking-[-0.06em] sm:text-6xl">Une meilleure façon de <span className="text-coral">travailler ensemble.</span></h2><p className="mt-5 max-w-md text-base leading-7 text-ink/55">Pas de bruit, pas de perte de temps. DevConnect vous aide à formuler, trouver, comparer et avancer — au même endroit.</p><Link href="/publier" className="mt-7 inline-flex items-center gap-2 rounded-full bg-ink px-5 py-3.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#26323a]">Commencer maintenant <ArrowRight size={16} /></Link></div><div id="fonctionnement" className="grid gap-3 sm:grid-cols-2"><div className="rounded-[24px] bg-ink p-6 text-white sm:translate-y-8"><span className="font-display text-5xl font-bold text-[#f4a35d]">01</span><h3 className="mt-12 font-display text-xl font-bold">Publiez votre besoin</h3><p className="mt-3 text-sm leading-6 text-white/55">Un brief clair, une catégorie, un budget. Les bons profils comprennent immédiatement votre contexte.</p></div><div className="rounded-[24px] border border-ink/10 bg-[#eaf0ff] p-6"><span className="font-display text-5xl font-bold text-[#1557f5]">02</span><h3 className="mt-12 font-display text-xl font-bold">Comparez les propositions</h3><p className="mt-3 text-sm leading-6 text-ink/55">Parcourez les profils, échangez et choisissez la personne avec qui le courant passe.</p></div><div className="rounded-[24px] border border-ink/10 bg-[#fff1ed] p-6 sm:translate-y-8"><span className="font-display text-5xl font-bold text-[#e4793f]">03</span><h3 className="mt-12 font-display text-xl font-bold">Faites avancer le projet</h3><p className="mt-3 text-sm leading-6 text-ink/55">Suivez les livrables et gardez chaque conversation au même endroit.</p></div><div className="rounded-[24px] border border-ink/10 bg-[#edf8f0] p-6"><span className="font-display text-5xl font-bold text-[#318653]">04</span><h3 className="mt-12 font-display text-xl font-bold">Construisez la suite</h3><p className="mt-3 text-sm leading-6 text-ink/55">Évaluez l'expérience et retrouvez vos talents préférés pour la prochaine mission.</p></div></div></div></section>

      <section className="bg-ink py-20 text-white sm:py-28"><div className="container"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow eyebrow-light">Les profils à suivre</p><h2 className="mt-3 max-w-xl font-display text-4xl font-bold leading-[1.03] tracking-[-0.06em] sm:text-5xl">Des talents brillants, <span className="text-[#f4a35d]">partout en Afrique.</span></h2></div><Link href="/explorer" className="inline-flex w-fit items-center gap-2 text-sm font-bold text-[#f4a35d]">Voir tous les profils <ArrowRight size={16} /></Link></div><div className="mt-10 grid gap-4 sm:grid-cols-3">{freelancers.map((person) => <Link href="/explorer" key={person.name} className="group rounded-[24px] border border-white/10 bg-white/[0.06] p-5 transition hover:-translate-y-1 hover:bg-white/10"><div className="flex items-start justify-between"><span className={`grid h-14 w-14 place-items-center rounded-2xl ${person.tint} font-display text-lg font-bold text-ink`}>{person.initials}</span><span className="rounded-full bg-white/10 px-2.5 py-1 text-[10px] font-bold text-white/70">Disponible</span></div><h3 className="mt-7 font-display text-xl font-bold">{person.name}</h3><p className="mt-1 text-sm text-white/55">{person.role}</p><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-4 text-xs text-white/45"><span>{person.city}</span><span className="font-bold text-[#f4a35d]">★ {person.rating}</span></div></Link>)}</div></div></section>

      <section className="container py-20 sm:py-28"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="eyebrow">Pourquoi DevConnect</p><h2 className="mt-3 font-display text-4xl font-bold leading-[1.03] tracking-[-0.06em] sm:text-5xl">Pensé pour les réalités du <span className="text-coral">terrain.</span></h2></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-[22px] bg-[#f2f0eb] p-5"><CircleDollarSign size={22} className="text-coral" /><h3 className="mt-8 font-display text-lg font-bold">Clair sur les budgets</h3><p className="mt-2 text-sm leading-6 text-ink/55">Des fourchettes simples pour démarrer une vraie conversation.</p></div><div className="rounded-[22px] bg-[#eaf0ff] p-5"><Clock3 size={22} className="text-[#1557f5]" /><h3 className="mt-8 font-display text-lg font-bold">Rapide à prendre en main</h3><p className="mt-2 text-sm leading-6 text-ink/55">Un espace de travail qui va à l'essentiel, même sur mobile.</p></div><div className="rounded-[22px] bg-[#edf8f0] p-5"><Layers3 size={22} className="text-[#318653]" /><h3 className="mt-8 font-display text-lg font-bold">Fait pour durer</h3><p className="mt-2 text-sm leading-6 text-ink/55">Une architecture prête pour Firebase, le stockage média et les paiements.</p></div><div className="rounded-[22px] bg-[#f4edff] p-5"><LockKeyhole size={22} className="text-[#8a58d6]" /><h3 className="mt-8 font-display text-lg font-bold">Sécurité en construction</h3><p className="mt-2 text-sm leading-6 text-ink/55">Les paiements réels ne sont pas activés dans cette démo.</p></div></div></div></section>

      <section className="border-y border-ink/10 bg-[#f7f4ee] py-20 sm:py-24"><div className="container"><div className="mx-auto max-w-3xl text-center"><Quote className="mx-auto text-coral" size={34} /><blockquote className="mt-6 font-display text-3xl font-bold leading-tight tracking-[-0.04em] sm:text-5xl">“DevConnect rend enfin simple le fait de trouver quelqu'un qui comprend vraiment le marché africain.”</blockquote><div className="mt-7 flex items-center justify-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#eec6a8] text-xs font-bold">MN</span><div className="text-left"><p className="text-sm font-bold">Mariam Ndao</p><p className="text-xs text-ink/45">Fondatrice, Dakar Eats</p></div></div></div></div></section>

      <section className="container py-20 sm:py-28"><div className="relative overflow-hidden rounded-[32px] bg-[#1557f5] px-6 py-12 text-white sm:px-12 sm:py-16"><div className="absolute -right-12 -top-24 h-72 w-72 rounded-full border-[44px] border-white/10" /><div className="absolute -bottom-32 right-40 h-60 w-60 rounded-full border-[32px] border-[#f4a35d]/25" /><div className="relative flex flex-col justify-between gap-9 sm:flex-row sm:items-end"><div><p className="eyebrow text-white/60">Prêt à commencer ?</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-bold leading-[1.02] tracking-[-0.06em] sm:text-6xl">Votre prochain projet peut aller <span className="text-[#f4a35d]">plus loin.</span></h2></div><Link href="/publier" className="inline-flex w-fit shrink-0 items-center gap-2 rounded-full bg-white px-5 py-3.5 text-sm font-bold text-[#1557f5] transition hover:-translate-y-0.5 hover:bg-[#fdfcf9]">Publier un projet <ArrowRight size={17} /></Link></div></div></section>
    </main>
    <footer className="border-t border-ink/10 bg-[#fbfaf7] py-12 pb-28 sm:pb-12"><div className="container"><div className="flex flex-col justify-between gap-8 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-ink text-lg font-black text-white">B</span><span className="font-display text-[1.3rem] font-bold tracking-[-0.04em]">Dev<span className="text-coral">Connect</span></span></div><p className="mt-4 max-w-xs text-sm leading-6 text-ink/45">Le réseau africain des talents qui font avancer les idées.</p></div><div className="grid grid-cols-2 gap-x-12 gap-y-3 text-sm font-semibold text-ink/55 sm:flex sm:gap-8"><Link href="/explorer" className="hover:text-ink">Freelances</Link><Link href="/projets" className="hover:text-ink">Projets</Link><Link href="/connexion" className="hover:text-ink">Connexion</Link><a href="#fonctionnement" className="hover:text-ink">Aide</a></div></div><div className="mt-10 flex flex-col justify-between gap-3 border-t border-ink/10 pt-5 text-xs text-ink/35 sm:flex-row"><span>© 2026 DevConnect. Démo produit — données fictives.</span><span>Firebase · ImageKit · Cloudinary · paiements locaux : prêts à connecter</span></div></div></footer>
  </>;
}
