import { ArrowRight, BadgeCheck, Check, CircleDollarSign, Clock3, Code2, Layers3, LockKeyhole, Megaphone, Palette, Sparkles, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";
import { backend } from "@/lib/integrations";

const HERO_IMAGE = "/devconnect-hero.jpg";
const categories = [
  { name: "Développement web", icon: Code2, tint: "bg-[#e9f0ff] text-[#1557f5]", count: "Frontend, backend & full-stack" },
  { name: "Design & UI/UX", icon: Palette, tint: "bg-[#fff0e8] text-[#e4793f]", count: "Identité, produit & expérience" },
  { name: "IA & automatisation", icon: Sparkles, tint: "bg-[#f2edff] text-[#7955c9]", count: "Outils, agents & workflows" },
  { name: "Marketing digital", icon: Megaphone, tint: "bg-[#eaf7ef] text-[#318653]", count: "Acquisition, contenu & croissance" },
];

function SectionHeading({ eyebrow, title, link }: { eyebrow: string; title: React.ReactNode; link?: string }) {
  return <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">{eyebrow}</p><h2 className="mt-3 max-w-2xl font-display text-3xl font-bold leading-[1.05] tracking-[-.055em] text-ink sm:text-5xl">{title}</h2></div>{link && <Link href={link} className="inline-flex w-fit items-center gap-2 text-sm font-bold text-[#1557f5] transition hover:gap-3">Tout explorer <ArrowRight size={16} /></Link>}</div>;
}

function EmptyPanel({ title, body, href, action }: { title: string; body: string; href: string; action: string }) {
  return <div className="rounded-[28px] border border-dashed border-ink/15 bg-white p-8 text-center shadow-[0_10px_35px_rgba(19,28,35,.04)]"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#e9f0ff] text-[#1557f5]"><UsersRound size={20} /></span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-ink/50">{body}</p><Link href={href} className="mt-5 inline-flex items-center gap-2 rounded-full bg-ink px-5 py-3 text-sm font-bold text-white transition hover:bg-[#26323a]">{action} <ArrowRight size={15} /></Link></div>;
}

export default function Home() {
  const [counts, setCounts] = useState({ profiles: 0, projects: 0 });
  useEffect(() => { let active = true; (async () => { if (!backend) return; const [{ count: profiles }, { count: projects }] = await Promise.all([backend.from("profiles").select("id", { count: "exact", head: true }).eq("role", "developer"), backend.from("projects").select("id", { count: "exact", head: true }).eq("status", "open")]); if (active) setCounts({ profiles: profiles ?? 0, projects: projects ?? 0 }); })(); return () => { active = false; }; }, []);
  return <><main>
    <section className="relative overflow-hidden bg-ink text-white"><div className="absolute inset-0 opacity-80" style={{ backgroundImage: `url(${HERO_IMAGE})`, backgroundPosition: "center right", backgroundSize: "cover" }} /><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_35%,rgba(21,87,245,.32),transparent_32%),linear-gradient(90deg,#131c23_12%,rgba(19,28,35,.96)_44%,rgba(19,28,35,.2)_100%)]" /><div className="container relative flex min-h-[650px] items-center pb-16 pt-20 sm:min-h-[710px] sm:pb-24 sm:pt-24"><div className="max-w-3xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/[.08] px-3 py-2 text-xs font-semibold text-white/75 backdrop-blur"><span className="h-2 w-2 rounded-full bg-[#b9f227] shadow-[0_0_0_4px_rgba(185,242,39,.15)]" /> La marketplace des talents numériques africains</div><h1 className="max-w-3xl font-display text-5xl font-bold leading-[.94] tracking-[-.075em] sm:text-7xl lg:text-[88px]">Les idées locales méritent des <span className="text-[#b9f227]">talents extraordinaires.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/65 sm:text-lg">Trouvez les personnes capables de transformer votre prochaine idée en produit concret, avec un cadre clair et des profils authentiques.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/publier" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#b9f227] px-6 py-3.5 text-sm font-bold text-ink transition hover:-translate-y-0.5 hover:bg-[#caff4e]">Publier un projet <ArrowRight size={17} /></Link><Link href="/explorer" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/20 bg-white/10 px-6 py-3.5 text-sm font-bold text-white transition hover:bg-white/15">Explorer les profils <ArrowRight size={17} /></Link></div><div className="mt-12 flex flex-wrap items-center gap-x-8 gap-y-4 text-xs font-semibold text-white/50"><span className="flex items-center gap-2"><BadgeCheck size={16} className="text-[#b9f227]" /> Profils vérifiés</span><span className="flex items-center gap-2"><LockKeyhole size={16} className="text-[#b9f227]" /> Échanges protégés</span><span className="flex items-center gap-2"><UsersRound size={16} className="text-[#b9f227]" /> Communauté locale</span></div></div></div><div className="container relative -mb-1"><div className="grid gap-5 border-t border-white/10 py-6 text-xs text-white/45 sm:grid-cols-2"><span><strong className="mr-2 font-display text-2xl text-white">{counts.profiles}</strong> développeurs inscrits</span><span><strong className="mr-2 font-display text-2xl text-white">{counts.projects}</strong> projets ouverts</span></div></div></section>
    <section className="container py-20 sm:py-28"><SectionHeading eyebrow="Les expertises qui comptent" title={<>Tout ce qu'il faut pour passer de l'idée au <span className="text-coral">résultat.</span></>} link="/explorer" /><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{categories.map(({ name, icon: Icon, tint, count }) => <Link href="/explorer" key={name} className="group rounded-[24px] border border-ink/[.08] bg-white p-5 shadow-[0_8px_28px_rgba(19,28,35,.045)] transition duration-300 hover:-translate-y-1 hover:border-[#1557f5]/25 hover:shadow-[0_16px_35px_rgba(19,28,35,.09)]"><span className={`grid h-11 w-11 place-items-center rounded-2xl ${tint}`}><Icon size={20} /></span><h3 className="mt-8 font-display text-lg font-bold">{name}</h3><p className="mt-2 text-xs leading-5 text-ink/45">{count}</p><div className="mt-5 flex items-center justify-between border-t border-ink/[.08] pt-4 text-xs font-semibold text-ink/40"><span>Explorer</span><ArrowRight size={15} className="transition group-hover:translate-x-1" /></div></Link>)}</div></section>
    <section className="bg-[#f1f3f1] py-20 sm:py-28"><div className="container"><SectionHeading eyebrow="Une communauté qui démarre bien" title={<>Des profils et projets réels, <span className="text-coral">sans artifice.</span></>} link="/connexion" /><div className="mt-10"><EmptyPanel title="Construisons la première communauté" body="ONE-X Dev affiche uniquement les profils, projets et avis créés par de vrais utilisateurs. Inscrivez-vous pour faire partie des premiers membres." href="/connexion" action="Créer un compte" /></div></div></section>
    <section className="container py-20 sm:py-28"><div className="grid items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Simple par design</p><h2 className="mt-3 max-w-lg font-display text-4xl font-bold leading-[1.02] tracking-[-.06em] sm:text-6xl">Une meilleure façon de <span className="text-coral">travailler ensemble.</span></h2><p className="mt-5 max-w-md text-base leading-7 text-ink/55">Un espace clair pour formuler, trouver, comparer et avancer ensemble, sans faux témoignages ni chiffres inventés.</p><Link href="/connexion" className="mt-7 inline-flex items-center gap-2 rounded-full bg-ink px-5 py-3.5 text-sm font-bold text-white transition hover:bg-[#26323a]">Commencer maintenant <ArrowRight size={16} /></Link></div><div id="fonctionnement" className="grid gap-3 sm:grid-cols-2"><div className="rounded-[24px] bg-ink p-6 text-white sm:translate-y-8"><span className="font-display text-5xl font-bold text-[#b9f227]">01</span><h3 className="mt-12 font-display text-xl font-bold">Choisissez votre parcours</h3><p className="mt-3 text-sm leading-6 text-white/55">Client à la recherche d'un développeur ou professionnel qui propose ses compétences.</p></div><div className="rounded-[24px] border border-ink/10 bg-[#e9f0ff] p-6"><span className="font-display text-5xl font-bold text-[#1557f5]">02</span><h3 className="mt-12 font-display text-xl font-bold">Créez un profil précis</h3><p className="mt-3 text-sm leading-6 text-ink/55">Présentez votre besoin, votre métier, vos compétences et vos disponibilités.</p></div><div className="rounded-[24px] border border-ink/10 bg-[#fff0e8] p-6 sm:translate-y-8"><span className="font-display text-5xl font-bold text-[#e4793f]">03</span><h3 className="mt-12 font-display text-xl font-bold">Échangez clairement</h3><p className="mt-3 text-sm leading-6 text-ink/55">Discutez dans un cadre professionnel et gardez les informations importantes au même endroit.</p></div><div className="rounded-[24px] border border-ink/10 bg-[#eaf7ef] p-6"><span className="font-display text-5xl font-bold text-[#318653]">04</span><h3 className="mt-12 font-display text-xl font-bold">Construisez la suite</h3><p className="mt-3 text-sm leading-6 text-ink/55">Les avis et réalisations seront ajoutés uniquement après de vraies missions.</p></div></div></div></section>
    <section className="container pb-20 sm:pb-28"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-[22px] bg-[#f2f0eb] p-5"><CircleDollarSign size={22} className="text-coral" /><h3 className="mt-8 font-display text-lg font-bold">Budgets transparents</h3><p className="mt-2 text-sm leading-6 text-ink/55">Des informations réelles fournies par les porteurs de projet.</p></div><div className="rounded-[22px] bg-[#e9f0ff] p-5"><Clock3 size={22} className="text-[#1557f5]" /><h3 className="mt-8 font-display text-lg font-bold">Rapide à prendre en main</h3><p className="mt-2 text-sm leading-6 text-ink/55">Une expérience claire, pensée pour mobile et ordinateur.</p></div><div className="rounded-[22px] bg-[#eaf7ef] p-5"><Layers3 size={22} className="text-[#318653]" /><h3 className="mt-8 font-display text-lg font-bold">Profils authentiques</h3><p className="mt-2 text-sm leading-6 text-ink/55">Pas de comptes fictifs : chaque profil vient d'une inscription réelle.</p></div><div className="rounded-[22px] bg-[#f2edff] p-5"><Sparkles size={22} className="text-[#7955c9]" /><h3 className="mt-8 font-display text-lg font-bold">Avis vérifiables</h3><p className="mt-2 text-sm leading-6 text-ink/55">Les commentaires seront liés à des projets et utilisateurs identifiés.</p></div></div></section>
  </main><footer className="border-t border-ink/10 bg-[#fbfaf7] py-12 pb-28 sm:pb-12"><div className="container"><div className="flex flex-col justify-between gap-8 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2.5"><img src="/one-x-dev-logo.png" alt="ONE-X Dev" className="h-9 w-9 rounded-xl object-cover" /><span className="font-display text-[1.2rem] font-bold tracking-[-.04em]">ONE<span className="text-[#0878ed]">-X</span> Dev</span></div><p className="mt-4 max-w-xs text-sm leading-6 text-ink/45">Une marketplace authentique pour les talents du numérique.</p></div><div className="grid grid-cols-2 gap-x-12 gap-y-3 text-sm font-semibold text-ink/55 sm:flex sm:gap-8"><Link href="/explorer">Développeurs</Link><Link href="/projets">Projets</Link><Link href="/connexion">Connexion</Link><Link href="/aide">Aide</Link></div></div><div className="mt-10 border-t border-ink/10 pt-5 text-xs text-ink/35">© 2026 ONE-X Dev. Les contenus affichés sont créés par les utilisateurs.</div></div></footer></>;
}
