import { ArrowRight, Check, Code2, FileText, Heart, MessageCircle, Search, ShieldCheck, Sparkles, Star, UserRound, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useRoute } from "wouter";
import { supabase } from "@/lib/integrations";

const empty = (title: string, body: string, href = "/connexion", action = "Créer un compte") => <div className="rounded-[26px] border border-dashed border-ink/15 bg-white p-8 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#eaf0ff] text-[#1557f5]"><UserRound size={20} /></span><h2 className="mt-5 font-display text-xl font-bold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-ink/50">{body}</p><Link href={href} className="mt-5 inline-flex items-center gap-2 rounded-full bg-ink px-4 py-3 text-sm font-bold text-white">{action} <ArrowRight size={15} /></Link></div>;
const Intro = ({ eyebrow, title, body }: { eyebrow: string; title: React.ReactNode; body: string }) => <div><p className="eyebrow">{eyebrow}</p><h1 className="mt-3 max-w-3xl font-display text-4xl font-bold leading-[1.02] tracking-[-.06em] sm:text-6xl">{title}</h1><p className="mt-4 max-w-xl text-base leading-7 text-ink/55">{body}</p></div>;

type Profile = { id: string; full_name: string; username: string | null; role: string; avatar_url: string | null; bio: string | null; country: string | null; skills: string[]; availability: string };
type Project = { id: string; title: string; slug: string; description: string; category: string; budget_min: number | null; budget_max: number | null; currency: string; created_at: string };

function Avatar({ profile, large = false }: { profile: Pick<Profile, "full_name" | "avatar_url">; large?: boolean }) { return <div className={`overflow-hidden rounded-2xl bg-[#eaf0ff] ${large ? "h-24 w-24 text-3xl" : "h-16 w-16 text-lg"}`}>{profile.avatar_url ? <img src={profile.avatar_url} alt={`Photo de ${profile.full_name}`} className="h-full w-full object-cover" /> : <span className="grid h-full w-full place-items-center font-display font-bold text-[#1557f5]">{profile.full_name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase() || "U"}</span>}</div>; }

 export function FindDeveloperPage() { const [profiles, setProfiles] = useState<Profile[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { (async () => { if (!supabase) return setLoading(false); const { data } = await supabase.from("profiles").select("id, full_name, username, role, avatar_url, bio, country, skills, availability").eq("role", "developer").eq("availability", "available").order("created_at", { ascending: false }).limit(30); setProfiles((data ?? []) as Profile[]); setLoading(false); })(); }, []); return <main className="container py-10 sm:py-16"><Intro eyebrow="Trouver un développeur" title={<>Le bon profil pour faire passer votre projet au <span className="text-coral">niveau supérieur.</span></>} body="Découvrez uniquement les professionnels inscrits sur DevConnect, avec leurs compétences et leurs informations publiques." /><div className="mt-10 flex gap-3"><label className="relative flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-ink/35" size={18} /><input className="field bg-white pl-11" placeholder="Rechercher une compétence..." /></label><Link href="/publier" className="hidden items-center gap-2 rounded-full bg-ink px-5 py-3 text-sm font-bold text-white sm:inline-flex">Publier un projet <ArrowRight size={15} /></Link></div><div className="mt-10">{loading ? <p className="text-sm text-ink/45">Chargement des profils...</p> : profiles.length === 0 ? empty("Aucun développeur disponible pour le moment", "Les profils apparaîtront ici dès que de vrais développeurs auront terminé leur inscription.", "/connexion", "Je suis développeur") : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{profiles.map((profile) => <article key={profile.id} className="rounded-[24px] border border-ink/[.08] bg-white p-5 shadow-[0_6px_24px_rgba(19,28,35,.04)]"><div className="flex items-start justify-between"><Avatar profile={profile} /><button className="rounded-full p-2 text-ink/25" aria-label="Ajouter aux favoris"><Heart size={18} /></button></div><h2 className="mt-5 font-display text-lg font-bold">{profile.full_name}</h2><p className="mt-1 text-sm text-ink/50">{profile.bio || "Développeur sur DevConnect"}</p><div className="mt-4 flex flex-wrap gap-1.5">{(profile.skills ?? []).slice(0, 4).map((skill) => <span key={skill} className="rounded-md bg-[#fbfaf7] px-2 py-1 text-[11px] font-semibold text-ink/55">{skill}</span>)}</div><div className="mt-5 flex items-center justify-between border-t border-ink/10 pt-4 text-xs text-ink/45"><span>{profile.country || "Pays non renseigné"}</span><span className="flex items-center gap-1 text-[#318653]"><span className="h-1.5 w-1.5 rounded-full bg-[#318653]" />Disponible</span></div><Link href={`/profil/${profile.username || profile.id}`} className="mt-4 block rounded-xl bg-ink py-3 text-center text-sm font-bold text-white">Voir le profil</Link></article>)}</div>}</div></main>; }

export function ExploreProjectsPage() { const [projects, setProjects] = useState<Project[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { (async () => { if (!supabase) return setLoading(false); const { data } = await supabase.from("projects").select("id, title, slug, description, category, budget_min, budget_max, currency, created_at").eq("status", "open").order("created_at", { ascending: false }).limit(30); setProjects((data ?? []) as Project[]); setLoading(false); })(); }, []); return <main className="container py-10 sm:py-16"><Intro eyebrow="Projets publiés" title={<>Des missions réelles pour des talents qui veulent <span className="text-coral">construire.</span></>} body="Les opportunités affichées sont publiées par des clients inscrits. Aucun projet fictif n'est présenté." /><div className="mt-10">{loading ? <p className="text-sm text-ink/45">Chargement des projets...</p> : projects.length === 0 ? empty("Aucun projet ouvert pour le moment", "Les nouvelles missions apparaîtront ici dès qu’un client aura publié son premier projet.", "/publier", "Publier un projet") : <div className="grid gap-4">{projects.map((project) => <article key={project.id} className="rounded-[24px] border border-ink/[.08] bg-white p-6 shadow-[0_6px_24px_rgba(19,28,35,.04)] sm:p-7"><span className="rounded-full bg-[#f2f0eb] px-3 py-1 text-[10px] font-bold uppercase tracking-[.1em] text-ink/50">{project.category}</span><h2 className="mt-4 font-display text-xl font-bold sm:text-2xl">{project.title}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-ink/55">{project.description}</p><div className="mt-5 flex flex-wrap items-center justify-between gap-4 border-t border-ink/10 pt-4"><span className="font-display font-bold">{project.budget_min || project.budget_max ? `${project.budget_min ?? ""} – ${project.budget_max ?? ""} ${project.currency}` : "Budget à définir"}</span><Link href={`/projet/${project.slug}`} className="inline-flex items-center gap-2 text-sm font-bold text-[#1557f5]">Voir le projet <ArrowRight size={15} /></Link></div></article>)}</div>}</div></main>; }

export function ProjectDetailPage() { return <main className="container py-10 sm:py-16">{empty("Le projet sera visible après sa publication", "Cette page ne présente aucun exemple inventé. Connectez-vous pour publier ou consulter des projets réels.", "/connexion", "Se connecter")}</main>; }
export function DeveloperProfilePage() { return <main className="container py-10 sm:py-16"><div className="mx-auto max-w-3xl">{empty("Profil non disponible", "Les profils sont créés par les développeurs eux-mêmes. Les avis, commentaires et réalisations seront affichés uniquement après une inscription réelle.", "/connexion", "Créer mon profil")}<section className="mt-6 rounded-[26px] border border-ink/10 bg-white p-6 sm:p-8"><div className="flex items-center gap-3"><MessageCircle className="text-[#1557f5]" size={21} /><h2 className="font-display text-xl font-bold">Commentaires et avis</h2></div><p className="mt-3 text-sm leading-6 text-ink/50">Une interface moderne sera disponible après les premières missions : note, commentaire, date, projet lié et réponse du développeur.</p></section></div></main>; }

export function BecomeDeveloperPage() { return <main className="container py-10 sm:py-16"><div className="mx-auto max-w-3xl"><Intro eyebrow="Je suis développeur" title={<>Présentez votre talent avec <span className="text-coral">clarté.</span></>} body="Créez un profil professionnel avec votre spécialité, vos compétences, votre expérience et votre disponibilité." /><div className="mt-10 space-y-4">{["Votre identité et votre pays", "Votre spécialité principale", "Vos compétences et votre expérience", "Votre disponibilité et vos liens professionnels"].map((item, index) => <div key={item} className="flex items-center gap-4 rounded-2xl border border-ink/10 bg-white p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf0ff] font-display font-bold text-[#1557f5]">0{index + 1}</span><span className="font-semibold">{item}</span><Check className="ml-auto text-[#318653]" size={18} /></div>)}<Link href="/connexion" className="mt-4 inline-flex items-center gap-2 rounded-full bg-ink px-5 py-3.5 text-sm font-bold text-white">Commencer mon inscription <ArrowRight size={16} /></Link></div></div></main>; }

export function ClientDashboardPage() { return <main className="container py-10 sm:py-14"><Intro eyebrow="Espace client" title={<>Votre espace pour trouver un <span className="text-coral">développeur.</span></>} body="Publiez vos besoins et suivez vos échanges dans un espace privé." /><div className="mt-10">{empty("Votre tableau de bord est vide", "Vos projets, propositions et messages apparaîtront ici après votre inscription et votre première publication.", "/publier", "Publier un projet")}</div></main>; }
export function DeveloperDashboardPage() { const cards = [{ Icon: WalletCards, label: "Revenus", value: "0" }, { Icon: FileText, label: "Propositions", value: "0" }, { Icon: Star, label: "Avis reçus", value: "0" }]; return <main className="container py-10 sm:py-14"><Intro eyebrow="Espace développeur" title={<>Votre espace pour développer votre <span className="text-coral">activité.</span></>} body="Votre profil, vos missions et vos revenus seront affichés ici." /><div className="mt-10 grid gap-4 sm:grid-cols-3">{cards.map(({ Icon, label, value }) => <div key={label} className="rounded-[22px] border border-ink/10 bg-white p-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf0ff] text-[#1557f5]"><Icon size={18} /></div><p className="mt-5 text-sm text-ink/45">{label}</p><p className="mt-1 font-display text-4xl font-bold">{value}</p></div>)}</div><div className="mt-8">{empty("Aucune mission pour le moment", "Les projets ouverts correspondant à vos compétences apparaîtront ici.", "/projets", "Explorer les projets")}</div></main>; }
export function HelpSecurityPage() { const cards = [{ Icon: ShieldCheck, title: "Profils authentiques" }, { Icon: MessageCircle, title: "Commentaires liés aux missions" }, { Icon: Code2, title: "Compétences déclarées" }]; return <main className="container py-10 sm:py-16"><Intro eyebrow="Aide et confiance" title={<>Une expérience claire, des échanges <span className="text-coral">professionnels.</span></>} body="DevConnect protège la qualité des profils, des projets et des commentaires grâce à des données liées aux comptes réels." /><div className="mt-10 grid gap-4 sm:grid-cols-3">{cards.map(({ Icon, title }) => <div key={title} className="rounded-[22px] border border-ink/10 bg-white p-6"><Icon className="text-[#1557f5]" size={22} /><h2 className="mt-7 font-display text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-ink/50">Cette fonctionnalité s’appuie sur les données réelles de votre compte.</p></div>)}</div></main>; }
